// frontend/src/domains/moodboard/components/MoodboardEditor.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Moodboard } from '../model/Moodboard'

defineProps<{
  moodboard: Moodboard | null
}>()

const emit = defineEmits<{
  upload: [files: File[]]
}>()

const isDragging = ref(false)
const fileInputRef = ref<HTMLInputElement | null>(null)

function handleDrop(e: DragEvent) {
  isDragging.value = false
  const files = Array.from(e.dataTransfer?.files || [])
  if (files.length > 0) emit('upload', files)
}

function handleFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const files = Array.from(input.files || [])
  if (files.length > 0) emit('upload', files)
  input.value = ''
}
</script>

<template>
  <div class="moodboard-editor">
    <h3 class="section-title">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/>
        <rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>
      </svg>
      Moodboard
      <span v-if="moodboard" class="count-badge">{{ moodboard.imageUrls.length }}</span>
    </h3>

    <!-- Upload Zone (shown when no moodboard or to add more) -->
    <div
      class="drop-zone"
      :class="{ dragging: isDragging }"
      @dragover.prevent="isDragging = true"
      @dragleave="isDragging = false"
      @drop.prevent="handleDrop"
      @click="fileInputRef?.click()"
    >
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="drop-icon">
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
        <circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/>
      </svg>
      <p class="drop-text">Add reference images for style and mood</p>
      <p class="drop-hint">Drop multiple images or click to browse</p>
      <input
        ref="fileInputRef"
        type="file"
        accept="image/*"
        multiple
        class="file-input-hidden"
        @change="handleFileChange"
      />
    </div>

    <!-- Image Gallery -->
    <div v-if="moodboard && moodboard.imageUrls.length > 0" class="image-gallery">
      <div v-for="(url, idx) in moodboard.imageUrls" :key="idx" class="gallery-item">
        <img :src="url" alt="moodboard reference" />
      </div>
    </div>

    <!-- Characteristics -->
    <div v-if="moodboard?.characteristics" class="characteristics">
      <span class="char-label">Style Notes</span>
      <p class="char-text">{{ moodboard.characteristics }}</p>
    </div>

    <!-- Combined URL -->
    <div v-if="moodboard?.combinedUrl" class="combined-preview">
      <span class="char-label">Combined Moodboard</span>
      <div class="combined-thumb">
        <img :src="moodboard.combinedUrl" alt="combined moodboard" />
      </div>
    </div>
  </div>
</template>

<style scoped>
.moodboard-editor {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 1rem;
  font-weight: 600;
  color: var(--color-text);
}

.count-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 22px;
  height: 22px;
  padding: 0 6px;
  background: var(--color-primary-light);
  color: var(--color-primary);
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
}

/* Drop Zone */
.drop-zone {
  border: 2px dashed var(--color-border);
  border-radius: var(--radius-md);
  padding: 32px 20px;
  text-align: center;
  cursor: pointer;
  transition: all var(--transition);
  background: var(--color-bg);
}

.drop-zone:hover {
  border-color: var(--color-primary-subtle);
  background: var(--color-primary-light);
}

.drop-zone.dragging {
  border-color: var(--color-primary);
  background: var(--color-primary-light);
}

.drop-icon {
  color: var(--color-text-muted);
  margin-bottom: 8px;
}

.drop-text {
  font-size: 0.875rem;
  color: var(--color-text-secondary);
  font-weight: 500;
}

.drop-hint {
  font-size: 0.75rem;
  color: var(--color-text-muted);
  margin-top: 4px;
}

.file-input-hidden {
  display: none;
}

/* Gallery */
.image-gallery {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 8px;
}

.gallery-item {
  aspect-ratio: 1;
  border-radius: var(--radius-sm);
  overflow: hidden;
  background: var(--color-border-light);
  border: 1px solid var(--color-border-light);
  transition: all var(--transition);
}

.gallery-item:hover {
  border-color: var(--color-primary-subtle);
  box-shadow: var(--shadow-sm);
}

.gallery-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

/* Characteristics */
.characteristics {
  padding: 12px 14px;
  background: var(--color-bg);
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border-light);
}

.char-label {
  display: block;
  font-size: 0.6875rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--color-text-muted);
  font-weight: 600;
  margin-bottom: 6px;
}

.char-text {
  font-size: 0.8125rem;
  color: var(--color-text-secondary);
  line-height: 1.5;
}

/* Combined */
.combined-preview {
  padding: 12px 14px;
  background: var(--color-bg);
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border-light);
}

.combined-thumb {
  border-radius: var(--radius-sm);
  overflow: hidden;
  margin-top: 8px;
}

.combined-thumb img {
  width: 100%;
  border-radius: var(--radius-sm);
}
</style>

// frontend/src/domains/moodboard/components/MoodboardEditor.tsx
import { useState, useRef } from 'react'
import type { Moodboard } from '../model/Moodboard'

interface MoodboardEditorProps {
  moodboard: Moodboard | null
  onUpload: (files: File[]) => void
}

export default function MoodboardEditor({ moodboard, onUpload }: MoodboardEditorProps) {
  const [isDragging, setIsDragging] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  function handleDrop(e: React.DragEvent) {
    e.preventDefault()
    setIsDragging(false)
    const files = Array.from(e.dataTransfer?.files || [])
    if (files.length > 0) onUpload(files)
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const files = Array.from(e.target.files || [])
    if (files.length > 0) onUpload(files)
    e.target.value = ''
  }

  return (
    <div className="flex flex-col gap-4">
      <h3 className="flex items-center gap-2 text-base font-semibold text-text">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/>
          <rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>
        </svg>
        Moodboard
        {moodboard && <span className="inline-flex items-center justify-center min-w-[22px] h-[22px] px-1.5 bg-primary-light text-primary rounded-full text-xs font-semibold">{moodboard.imageUrls.length}</span>}
      </h3>

      <div
        className={`border-2 border-dashed rounded-[var(--radius-md)] py-8 px-5 text-center cursor-pointer transition-all duration-200 ${
          isDragging ? 'border-primary bg-primary-light' : 'border-border bg-bg hover:border-primary-subtle hover:bg-primary-light'
        }`}
        onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
        onDragLeave={() => setIsDragging(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
      >
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-text-muted mb-2 mx-auto">
          <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/>
        </svg>
        <p className="text-sm text-text-secondary font-medium">Add reference images for style and mood</p>
        <p className="text-xs text-text-muted mt-1">Drop multiple images or click to browse</p>
        <input ref={fileInputRef} type="file" accept="image/*" multiple className="hidden" onChange={handleFileChange} />
      </div>

      {moodboard && moodboard.imageUrls.length > 0 && (
        <div className="grid grid-cols-[repeat(auto-fill,minmax(100px,1fr))] gap-2">
          {moodboard.imageUrls.map((url, idx) => (
            <div key={idx} className="aspect-square rounded-[var(--radius-sm)] overflow-hidden bg-border-light border border-border-light transition-all duration-200 hover:border-primary-subtle hover:shadow-sm">
              <img src={url} alt="moodboard reference" className="w-full h-full object-cover" />
            </div>
          ))}
        </div>
      )}

      {moodboard?.characteristics && (
        <div className="py-3 px-3.5 bg-bg rounded-[var(--radius-md)] border border-border-light">
          <span className="block text-[0.6875rem] uppercase tracking-wide text-text-muted font-semibold mb-1.5">Style Notes</span>
          <p className="text-[0.8125rem] text-text-secondary leading-relaxed">{moodboard.characteristics}</p>
        </div>
      )}

      {moodboard?.combinedUrl && (
        <div className="py-3 px-3.5 bg-bg rounded-[var(--radius-md)] border border-border-light">
          <span className="block text-[0.6875rem] uppercase tracking-wide text-text-muted font-semibold mb-1.5">Combined Moodboard</span>
          <div className="rounded-[var(--radius-sm)] overflow-hidden mt-2">
            <img src={moodboard.combinedUrl} alt="combined moodboard" className="w-full rounded-[var(--radius-sm)]" />
          </div>
        </div>
      )}
    </div>
  )
}
