// frontend/src/domains/sketch/components/SketchUploader.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Sketch } from '../model/Sketch'

defineProps<{
  sketches: Sketch[]
}>()

const emit = defineEmits<{
  upload: [file: File]
  remove: [id: string]
}>()

const isDragging = ref(false)
const fileInputRef = ref<HTMLInputElement | null>(null)

function handleDrop(e: DragEvent) {
  isDragging.value = false
  const file = e.dataTransfer?.files[0]
  if (file) emit('upload', file)
}

function handleFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (file) emit('upload', file)
  input.value = ''
}
</script>

<template>
  <div class="sketch-uploader">
    <h3 class="section-title">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
        <polyline points="17 8 12 3 7 8"/>
        <line x1="12" y1="3" x2="12" y2="15"/>
      </svg>
      Sketches
      <span class="count-badge">{{ sketches.length }}</span>
    </h3>

    <!-- Upload Zone -->
    <div
      class="drop-zone"
      :class="{ dragging: isDragging }"
      @dragover.prevent="isDragging = true"
      @dragleave="isDragging = false"
      @drop.prevent="handleDrop"
      @click="fileInputRef?.click()"
    >
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="drop-icon">
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
        <polyline points="17 8 12 3 7 8"/>
        <line x1="12" y1="3" x2="12" y2="15"/>
      </svg>
      <p class="drop-text">Drop sketch files here or click to browse</p>
      <p class="drop-hint">PNG, JPG up to 20MB</p>
      <input
        ref="fileInputRef"
        type="file"
        accept="image/*"
        multiple
        class="file-input-hidden"
        @change="handleFileChange"
      />
    </div>

    <!-- Sketch List -->
    <div v-if="sketches.length > 0" class="sketch-list">
      <div v-for="sketch in sketches" :key="sketch.id" class="sketch-item">
        <div class="sketch-thumb">
          <img :src="sketch.imageUrl" :alt="sketch.filename" />
        </div>
        <div class="sketch-info">
          <span class="sketch-name">{{ sketch.filename }}</span>
          <span class="sketch-order">Order: {{ sketch.sortOrder }}</span>
        </div>
        <button class="remove-btn" title="Remove" @click="emit('remove', sketch.id)">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.sketch-uploader {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 1rem;
  font-weight: 600;
  color: var(--color-text);
}

.count-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 22px;
  height: 22px;
  padding: 0 6px;
  background: var(--color-primary-light);
  color: var(--color-primary);
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
}

/* Drop Zone */
.drop-zone {
  border: 2px dashed var(--color-border);
  border-radius: var(--radius-md);
  padding: 32px 20px;
  text-align: center;
  cursor: pointer;
  transition: all var(--transition);
  background: var(--color-bg);
}

.drop-zone:hover {
  border-color: var(--color-primary-subtle);
  background: var(--color-primary-light);
}

.drop-zone.dragging {
  border-color: var(--color-primary);
  background: var(--color-primary-light);
}

.drop-icon {
  color: var(--color-text-muted);
  margin-bottom: 8px;
}

.drop-text {
  font-size: 0.875rem;
  color: var(--color-text-secondary);
  font-weight: 500;
}

.drop-hint {
  font-size: 0.75rem;
  color: var(--color-text-muted);
  margin-top: 4px;
}

.file-input-hidden {
  display: none;
}

/* Sketch List */
.sketch-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.sketch-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  background: var(--color-bg);
  border: 1px solid var(--color-border-light);
  border-radius: var(--radius-md);
  transition: all var(--transition);
}

.sketch-item:hover {
  border-color: var(--color-border);
}

.sketch-thumb {
  width: 48px;
  height: 48px;
  border-radius: var(--radius-sm);
  overflow: hidden;
  flex-shrink: 0;
  background: var(--color-border-light);
}

.sketch-thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.sketch-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.sketch-name {
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--color-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.sketch-order {
  font-size: 0.6875rem;
  color: var(--color-text-muted);
}

.remove-btn {
  width: 30px;
  height: 30px;
  border: none;
  background: transparent;
  color: var(--color-text-muted);
  border-radius: var(--radius-sm);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  transition: all var(--transition);
}

.remove-btn:hover {
  background: var(--color-danger-light);
  color: var(--color-danger);
}
</style>

// frontend/src/domains/sketch/components/SketchUploader.tsx
import { useState, useRef } from 'react'
import type { Sketch } from '../model/Sketch'

interface SketchUploaderProps {
  sketches: Sketch[]
  onUpload: (file: File) => void
  onRemove: (id: string) => void
}

export default function SketchUploader({ sketches, onUpload, onRemove }: SketchUploaderProps) {
  const [isDragging, setIsDragging] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  function handleDrop(e: React.DragEvent) {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer?.files[0]
    if (file) onUpload(file)
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (file) onUpload(file)
    e.target.value = ''
  }

  return (
    <div className="flex flex-col gap-4">
      <h3 className="flex items-center gap-2 text-base font-semibold text-text">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
          <polyline points="17 8 12 3 7 8"/>
          <line x1="12" y1="3" x2="12" y2="15"/>
        </svg>
        Sketches
        <span className="inline-flex items-center justify-center min-w-[22px] h-[22px] px-1.5 bg-primary-light text-primary rounded-full text-xs font-semibold">{sketches.length}</span>
      </h3>

      <div
        className={`border-2 border-dashed rounded-[var(--radius-md)] py-8 px-5 text-center cursor-pointer transition-all duration-200 ${
          isDragging ? 'border-primary bg-primary-light' : 'border-border bg-bg hover:border-primary-subtle hover:bg-primary-light'
        }`}
        onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
        onDragLeave={() => setIsDragging(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
      >
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-text-muted mb-2 mx-auto">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
          <polyline points="17 8 12 3 7 8"/>
          <line x1="12" y1="3" x2="12" y2="15"/>
        </svg>
        <p className="text-sm text-text-secondary font-medium">Drop sketch files here or click to browse</p>
        <p className="text-xs text-text-muted mt-1">PNG, JPG up to 20MB</p>
        <input ref={fileInputRef} type="file" accept="image/*" multiple className="hidden" onChange={handleFileChange} />
      </div>

      {sketches.length > 0 && (
        <div className="flex flex-col gap-2">
          {sketches.map((sketch) => (
            <div key={sketch.id} className="flex items-center gap-3 py-2.5 px-3 bg-bg border border-border-light rounded-[var(--radius-md)] transition-all duration-200 hover:border-border">
              <div className="w-12 h-12 rounded-[var(--radius-sm)] overflow-hidden shrink-0 bg-border-light">
                <img src={sketch.imageUrl} alt={sketch.filename} className="w-full h-full object-cover" />
              </div>
              <div className="flex-1 min-w-0 flex flex-col gap-0.5">
                <span className="text-[0.8125rem] font-medium text-text overflow-hidden text-ellipsis whitespace-nowrap">{sketch.filename}</span>
                <span className="text-[0.6875rem] text-text-muted">Order: {sketch.sortOrder}</span>
              </div>
              <button
                className="w-[30px] h-[30px] border-none bg-transparent text-text-muted rounded-[var(--radius-sm)] flex items-center justify-center shrink-0 transition-all duration-200 hover:bg-danger-light hover:text-danger"
                title="Remove"
                onClick={() => onRemove(sketch.id)}
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
